## default target:
# [build]
# target = "thumbv7em-none-eabihf"

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]

[target.thumbv7em-none-eabihf]
rustflags = ["-C", "target-cpu=cortex-m4"]


[unstable]
per-package-target = true
