[package]
main = "init"
name = "Hello, Flipper" # optional, default is crate name
# id = "hello-fap"                 # optional, default is crate name
# type = "FlipperAppType.EXTERNAL" # optional, default is FlipperAppType.EXTERNAL
# icon-file = "icon_10px.png"      # optional, path relative to the root of crate
# category = "Misc"                # optional, default Misc
# documentation: https://docs.rs/fam
