# Checks Flipper's HEADs.
# Check out latest RC and release versions and try to build with it.

# master contains tag fw-x.x.x(-rc) =>
#   - get latest "fw-" tag
#   - compare with current
#   - run tests with "fw-" tag as rev
#   - push te tag

name: SDK
on:
  schedule:
    - cron: "0 0 * * 0,1,5"

defaults:
  run:
    shell: bash

env:
  FLIPPER_FW_SRC_PATH: ${{ github.workspace }}/fz_fw/
  FLIPPER_REPO_CLONE_PATH: ${{ github.workspace }}/fz_fw/

jobs:
  tag:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        rev:
          - release
          - release-candidate

    steps:
      - name: checkout this
        uses: actions/checkout@v3

      - name: checkout sdk
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware
          path: ${{ env.FLIPPER_FW_SRC_PATH }}
          ref: ${{ matrix.rev }}
          submodules: false
          clean: false
          fetch-depth: 1

      - name: self tag
        id: self
        run: |
          git fetch --tags --quiet
          # get latest tag for this head:
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

          # get all tags starting from `commit-hash`:
          # git show-ref --tags -d | grep ^{commit-hash} | sed -e 's,.* refs/tags/,,' -e 's/\^{}//'

      - name: sdk tag
        id: sdk
        run: |
          cd $FLIPPER_FW_SRC_PATH
          git fetch --tags --quiet
          # get tag exactly points to this head:
          TAG="$(git tag --points-at HEAD)"
          echo "Current sdk ver: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # is current sdk version presents as tag on exactly this commit:
      - name: check current commit tags
        if: steps.sdk.outputs.tag
        id: current
        run: VALUE="$(
          git show-ref --tags -d |
          grep ^$(git rev-parse --short HEAD) |
          sed -e 's,.* refs/tags/,,' -e 's/\^{}//' |
          grep ^fw-${{ steps.sdk.outputs.tag }} || echo '')"
          echo "exists=$VALUE" >> $GITHUB_OUTPUT

    outputs:
      sdk: ${{ steps.sdk.outputs.tag }}
      tag: fw-${{ steps.sdk.outputs.tag }}
      continue: ${{ !steps.current.outputs.exists }}

  tests:
    needs: tag
    if: needs.tag.outputs.continue
    uses: ./.github/workflows/tests.yml
    with:
      rev: ${{ needs.tag.outputs.sdk }}

  finally:
    needs: [tag, tests]
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: push tag
        run: |
          TAG_DESCR="tested with fw ver ${{ needs.tag.outputs.sdk }} \
            (https://github.com/flipperdevices/flipperzero-firmware/releases/tag/${{ needs.tag.outputs.sdk }})"
          git tag -fa ${{ needs.tag.outputs.tag }} -m "$TAG_DESCR"
          echo "Pushing tag ${{ needs.tag.outputs.tag }}"
          git push --force origin refs/tags/${{ needs.tag.outputs.tag }}:refs/tags/${{ needs.tag.outputs.tag }}
