# Checks Flipper's HEADs.
# Check out latest RC and release versions and try to build with it.

# master contains tag fw-x.x.x(-rc) =>
#   - get latest "fw-" tag
#   - compare with current
#   - run tests with "fw-" tag as rev
#   - push te tag

name: SDK
on:
  schedule:
    - cron: "0 17 * * *"

defaults:
  run:
    shell: bash

env:
  FLIPPER_FW_SRC_PATH: ${{ github.workspace }}/fz_fw/
  FLIPPER_REPO_CLONE_PATH: ${{ github.workspace }}/fz_fw/

jobs:
  tag:
    name: Checkout
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        branch:
          - release
          - release-candidate

    steps:
      - name: checkout this
        uses: actions/checkout@v3

      - name: checkout sdk
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware
          path: ${{ env.FLIPPER_FW_SRC_PATH }}
          ref: ${{ matrix.branch }}
          submodules: false
          clean: false
          fetch-depth: 1

      - name: self tag
        id: self
        run: |
          git fetch --tags --quiet
          # get latest tag for this head:
          echo "$(git describe --tags --abbrev=0)"
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

          # get all tags starting from `commit-hash`:
          # git show-ref --tags -d | grep ^{commit-hash} | sed -e 's,.* refs/tags/,,' -e 's/\^{}//'

      - name: sdk tag
        id: sdk
        run: |
          cd $FLIPPER_FW_SRC_PATH
          git fetch --tags --quiet
          # get tag exactly points to this head:
          TAG="$(git tag --points-at HEAD)"
          echo "Current sdk ver: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # is current sdk version presents as tag on exactly this commit:
      - name: check current commit tags
        if: steps.sdk.outputs.tag
        id: exists
        run: |
          VALUE="$(                                                 \
          git show-ref --tags -d |                                  \
          grep ^$(git rev-parse --short HEAD) |                     \
          sed -e 's,.* refs/tags/,,' -e 's/\^{}//' |                \
          grep '^fw-${{ steps.sdk.outputs.tag }}$' || echo '')"
          echo "value=\"$VALUE\""
          echo "value=$VALUE" >> $GITHUB_OUTPUT

      - name: output [${{ steps.exists.outputs.value }}]
        id: output
        if: (!steps.exists.outputs.value)
        run: |
          echo 'out: ${{ matrix.branch }}=${{ steps.sdk.outputs.tag }}'
          echo '${{ matrix.branch }}=${{ steps.sdk.outputs.tag }}' >> $GITHUB_OUTPUT

    outputs:
      r: ${{ steps.output.outputs.release }}
      rc: ${{ steps.output.outputs.release-candidate }}

  test-r:
    name: Test [${{ needs.tag.outputs.r }}]
    needs: tag
    if: needs.tag.outputs.r
    uses: ./.github/workflows/tests.yml
    with:
      rev: ${{ needs.tag.outputs.r }}
      source: true
      examples: true
      prebuild: false
      support-crates: false
      style: false
      clippy: false

  test-rc:
    name: Test [${{ needs.tag.outputs.rc }}]
    needs: tag
    if: needs.tag.outputs.rc
    uses: ./.github/workflows/tests.yml
    with:
      rev: ${{ needs.tag.outputs.rc }}
      source: true
      examples: true
      prebuild: false
      support-crates: false
      style: false
      clippy: false

  set:
    name: Tag
    needs: [tag, test-r, test-rc]
    if: always() && (needs.test-r.result == 'success' || needs.test-rc.result == 'success')
    uses: ./.github/workflows/set-tag.yml
    with:
      # tags: ${{ toJSON(needs.tag.outputs.*) }}
      tags: >-
        [
        ${{ needs.test-r.result == 'success' && format('"fw-{0}",', needs.tag.outputs.r) || '' }}
        ${{ needs.test-rc.result == 'success' && format('"fw-{0}",', needs.tag.outputs.rc) || '' }}
        ]
      annotation: |
        Tested with fw ver {0}
        Link: https://github.com/flipperdevices/flipperzero-firmware/releases/tag/{0} .
