name: Tagger
on:
  workflow_call:
    inputs:
      tags:
        description: Array of tags `[tag,..]`
        required: true
        type: string
      annotation:
        description: Tag annotation template where `{0}` replaces with a tag.
        required: false
        type: string
      prefix:
        description: Prefix for tag used for git but not in annotation. e.g. `v`.
        required: false
        type: string
        default: ""

defaults:
  run:
    shell: bash

jobs:
  set:
    name: Tag
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: ${{ fromJSON(inputs.tags).* }}

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.head_commit.id }}

      - name: setup git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: push tag
        run: |
          TAG="${{ inputs.prefix }}${{ matrix.tag }}"
          git tag -fa $TAG -m '${{ format(inputs.annotation || '', matrix.tag) }}'
          echo "Pushing tag $TAG"
          git push --force origin refs/tags/$TAG:refs/tags/$TAG
